### ISSUE TITLE
using FaaS to run python

### ISSUE THREAD

**Issue by antonvanniekerk** [oracle-samples/usage-reports-to-adw#24]
Would it be possible to run the extract and load scripts as FaaS rather than needing to install an infra server for extracting the info ?

**Comment by adizohar** [comment]
FaaS has limitation of 5 minutes execution, for some customers the files are too big to load in 5 minutes, 
Additional, there is another project that loading the data using PLSQL packages on the ADB
This project uses compute to load, it can cater any customer size and file sizes
For your info.

**Comment by antonvanniekerk** [comment]
Hi, 

 

Do you maybe have a link to the plsql based project ?

 

I can find info on using ATP views but the information there is a little limited.

 

Appreciate it

 

Regards

 

Anton van niekerk

**Comment by adizohar** [comment]
The adbas tool - https://github.com/oracle-samples/adbs-tools
Here also example on FaaS from long ago - https://github.com/darenr/oci-usage-to-adw-function
