### ISSUE TITLE
Apex Application Version Issue

### ISSUE THREAD

**Issue by HimanshuSinha2015** [oracle-samples/usage-reports-to-adw#31]
Will you be able to provide the Apex application 22.2 release version?

**Comment by adizohar** [comment]
You can find version 22.2.4 [here](https://raw.githubusercontent.com/oracle/oci-python-sdk/release_2023-05-30/examples/usage_reports_to_adw/apex_demo_app/usage.demo.apex.sql)

Please bear in mind, it is old version and does not have new features added the last year

**Comment by HimanshuSinha2015** [comment]
Thanks.

**Comment by tiagorosa80** [comment]
Hello, when I try to create the secret it asks for the ADW OCID. I'm confused, can you help me?

From what I saw, ADW will be created on the terraform stack.

Thanks.

**Comment by adizohar** [comment]
Is it a new issue or same issue as above ? 
Can you share some more info, the secret you need to create in the console, the application does not create secret
If this is new issue, please open new issue number, closing this because  it is not relevant

**Comment by tiagorosa80** [comment]
sorry for the inconvenient

**Comment by adizohar** [comment]
Do you still have issue ? did you try to create the secret on the console ?

**Comment by tiagorosa80** [comment]
Worked perfectly. I had to create a separate secret and it worked perfectly. Thank you for your efforts, your application is magnificent, fantastic. The reports are excellent. Thank you very much.

**Comment by adizohar** [comment]
Thank you for the feedback, Appreciate it
