### ISSUE TITLE
Installation using terraforms fails to create dynamic group 

### ISSUE THREAD

**Issue by puneethvelichala** [oracle-samples/usage-reports-to-adw#34]
Installation using terraforms fails to create dynamic group with below error. I am trying to create resources in phoenix however my home region is ashburn.

Error: 403-NotAllowed, Please go to your home region IAD to execute CREATE, UPDATE and DELETE operations.

**Comment by adizohar** [comment]
Hi Puneet,
If you would like to create on different region, you need to create the IAM Dynamic Groups and policies in advance.
The terraform for IAM Dynamic groups and policies restricted to existing region
For your info

**Comment by puneethvelichala** [comment]
Thanks , I was able to complete the installation.

**Comment by adizohar** [comment]
Thank you !
