### ISSUE TITLE
After installation is successfully completed don't see oci package on the compute VM

### ISSUE THREAD

**Issue by puneethvelichala** [oracle-samples/usage-reports-to-adw#35]
I was able to follow the step by step instructions to complete the installation successfully and was able to upload data to ADW and view the reports from APEX application from Child tenancy , however i try to configure the authentication settings to upload reports for parent tenancy by following how to section 3.2 i don't see the oci package installed on the linux VM.

[opc@usage2adwvm ~]$ which oci
/usr/bin/which: no oci in (/home/opc/.local/bin:/home/opc/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/lib/oracle/current/client64/bin:/usr/lib/oracle/current/client64/bin)

**Comment by adizohar** [comment]
oci package does not installed by default, you can install it using the below commands:
pip3 install oci
