### ISSUE TITLE
Authorization failed or requested resource not found while retrieving Secret Vault using CLI

### ISSUE THREAD

**Issue by sataru15** [oracle-samples/usage-reports-to-adw#37]
Hi Support,

We are performing the "Enhance OCI Cost & Usage analytics using OAC" configuration in our OCI following the below blog.

https://blogs.oracle.com/futurestate/post/enhance-oci-cost-usage-analytics-using-oac

We are getting the below error when we try to retrieving the Secret Vault for the autonomous database. Kindly help us to fix the same.

###################################################################################
[opc@oiad1livlxdfs01 usage_reports_to_adw]$ python3 usage2adw_retrieve_secret.py -t local -secret ocid1.vaultsecret.oc1.iad.amaaaaaatn7irxaagpl2in4duqe6tcihkwswbnpdtnt23cc5wai3sbupz7da -check
Running Secret Retrieval from Vault
Starts at 2024-04-26 13:05:56

Connecting to Secret Client Service...
Connected.

ServiceError retrieving secret at get_secret_password !

{'target_service': 'secrets', 'status': 404, 'code': 'NotAuthorizedOrNotFound', 'opc-request-id': '06FCEDD0F1104ABFB9BBD5A679ED8233/6092164E0C21A5621EFDD22E6C54C19D/50F5794DB89573DAA632E93A7E44E231', 'message': 'Authorization failed or requested resource not found.', 'operation_name': 'get_secret_bundle', 'timestamp': '2024-04-26T13:05:57.289249+00:00', 'client_version': 'Oracle-PythonSDK/2.126.0', 'request_endpoint': 'GET https://secrets.vaults.us-ashburn-1.oci.oraclecloud.com/20190301/secretbundles/ocid1.vaultsecret.oc1.iad.amaaaaaatn7irxaagpl2in4duqe6tcihkwswbnpdtnt23cc5wai3sbupz7da', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_notauthorizedornotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/secretretrieval/20190301/SecretBundle/GetSecretBundle for details on this operation's requirements. If you are unable to resolve this secrets issue, please contact Oracle support

**Comment by sataru15** [comment]
![Uploading OCI Policy screenshot.PNG…]()

**Comment by adizohar** [comment]
Hi, please leave only instance.id in the dynamic group, remove the other conditions especially the resource_id = autonomous...

**Comment by sataru15** [comment]
Hi adizohar, Facing same issue even after performing the required modification.
![Uploading OCI Dynamic modified..PNG…]()

**Comment by adizohar** [comment]
Please make sure dynamic group is in form of:
ANY { instance.id = 'OCID_Of_Step_1_Instance' }
Please post print screen
Additional, which compartment the secret located ? is it in GlobalAnalytics ?

**Comment by sataru15** [comment]
Additional, which compartment the secret located ? is it in GlobalAnalytics ?
Yes

**Comment by adizohar** [comment]
I would believe the dynamic group is in the wrong domain, please create it in the Default domain

**Comment by adizohar** [comment]
Alternative, please add to the policy the domain initial like allow dynamic group identitycloud.../usage_download_group

**Comment by sataru15** [comment]
Please note then when we run the below command then the secret retrieval seems to be successful.
python3 usage2adw_download_adb_wallet.py -dbid ocid1.autonomousdatabas1.iad.abuwcljskucerdik4ysol7uz6c33gitikfbz73msz3hmcodldjetgdcau2ya -secret ocid1.vaultsecret.oc1.iad.amaaaaaatn7irxaagpl2in4duqe6tcihkwswbnpdtnt23cc5wai3sbupz7da -folder /home/opc/ADWUSG -zipfile /home/opc/ADWUSG/wallet.zip
![image](https://github.com/oracle-samples/usage-reports-to-adw/assets/168734604/c215cfe2-eaa7-4317-bda6-a185406f88cd)

**Comment by sataru15** [comment]
Not sure why it is failing for below command.
/home/opc/usage_reports_to_adw/usage2adw_setup.sh -setup_app

![image](https://github.com/oracle-samples/usage-reports-to-adw/assets/168734604/7fd73cd8-62c2-403c-8af5-45dc22770f99)

**Comment by adizohar** [comment]
How did you perform the installation ? Did you run the terraform or manual ? Which document did you follow ?

**Comment by sataru15** [comment]
> I would believe the dynamic group is in the wrong domain, please create it in the Default domain

Thank you for the update. This has fixed the issue.

**Comment by adizohar** [comment]
I am closing the ticket, if you have additional issue, please open new ticket, thank you !
