### ISSUE TITLE
How to Purge to OCI cost and usage data in ADW and reimport.

### ISSUE THREAD

**Issue by sataru15** [oracle-samples/usage-reports-to-adw#42]
we have imported only few months of data into our ADW DB. We would like to remove those data and import again.

**Comment by adizohar** [comment]
Please follow the howto document with all the answers
https://github.com/oracle-samples/usage-reports-to-adw/blob/main/step_by_step_howto.md

**Comment by adizohar** [comment]
Once you truncate the table, please update the file /home/opc/usage_reports_to_adw/config.user with correct date

**Comment by sataru15** [comment]
if we need full OCI usage and cost data then what should be the extract date value?

**Comment by adizohar** [comment]
The earliest data is from 2020 or 2021, you can use 2020-01
It will take time to load, are you using both usage files and cost files,  you can save storage by loading cost files only by skipping the usage files -su, you can add it to the file - run_multi_daily_usage2adw.sh
at the line python3 $APPDIR/usage2adw.py
