### ISSUE TITLE
Zero rows in the OCI_RESOURCES & OCI_INTERNAL_COST 

### ISSUE THREAD

**Issue by sataru15** [oracle-samples/usage-reports-to-adw#43]
Hi Support,

After the successful import of data from OCI to ADW we could see the below tables has only zero records. Kindly help us to check the same.

OCI_RESOURCES & OCI_INTERNAL_COST

**Comment by adizohar** [comment]
Hi 
OCI_RESOURCES is loaded using combined with showoci process
Here more information - [link](https://github.com/oracle-samples/usage-reports-to-adw/blob/main/step_by_step_howto.md#9-how-to-enable-showoci-extract-on-usage2adw-vm)

OCI_INTERNAL_COST is for internal purpose only and will not be populated for external customers
