### ISSUE TITLE
Relation between OCI tables in SQL query?

### ISSUE THREAD

**Issue by sataru15** [oracle-samples/usage-reports-to-adw#44]
Hi Support,

Can you please provide us the relation between the OCI cost and usage tables in sql query.

**Comment by adizohar** [comment]
You can read about usage and cost reports at [link](https://docs.oracle.com/en-us/iaas/Content/Billing/Concepts/usagereportsoverview.htm)

In general, there is no query to join both tables as raw data, if you aggregate resource_id you will be able to join using the resource_id
