### ISSUE TITLE
Unable to retrieve data

### ISSUE THREAD

**Issue by bmucherla** [oracle-samples/usage-reports-to-adw#46]
We configured the application and able to login to APEX, but we it is  not showing any data.  We schedule the cron jobs. 

Appreciate your help, 

Thanks
Bheeshma

**Comment by adizohar** [comment]
Can you please share how did you install the application, which installation method did you use ? Was it using terraform/manual setup ? 
Additional, can you share the output of the the execution of run_multi_daily_usage2adw.sh ?

**Comment by adizohar** [comment]
Closing the ticket as discussed and you succeed installing the application.
