### ISSUE TITLE
Error processing computation.

### ISSUE THREAD

**Issue by VARUNADITYAV** [oracle-samples/usage-reports-to-adw#59]
When I click run application "OCI Usage and Cost Report," I get the below error. please help. 
Error processing computation.
Technical Info (only available for developers)
is_internal_error: true
apex_error_code: APEX.COMPUTATION.UNHANDLED_ERROR
ora_sqlcode: -942
ora_sqlerrm: ORA-00942: table or view "WKSP_CFBFCC2Z2ZFM"."OCI_RESOURCES" does not exist
ORA-06512: at "APEX_240100.WWV_FLOW_COMPUTATION", line 317
ORA-06512: at "APEX_240100.WWV_FLOW_COMPUTATION", line 238
ORA-06512: at "APEX_240100.WWV_FLOW_DYNAMIC_EXEC", line 1618
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_240100", line 731
ORA-06512: at "SYS.DBMS_SYS_SQL", line 1579
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_240100", line 719
ORA-06512: at "APEX_240100.WWV_FLOW_DYNAMIC_EXEC", line 2014
ORA-06512: at "APEX_240100.WWV_FLOW_DYNAMIC_EXEC", line 1511
ORA-06512: at "APEX_240100.WWV_FLOW_DYNAMIC_EXEC", line 1634
ORA-06512: at "APEX_240100.WWV_FLOW_COMPUTATION", line 109
ORA-06512: at "APEX_240100.WWV_FLOW_COMPUTATION", line 306
component.type: APEX_APPLICATION_PAGES
component.id: 100000009999
component.name: OCI Usage and Cost Report - Sign In
error_backtrace:
ORA-06512: at "SYS.DBMS_SYS_SQL", line 1579
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_240100", line 719
ORA-06512: at "APEX_240100.WWV_FLOW_COMPUTATION", line 317
ORA-06512: at "APEX_240100.WWV_FLOW_COMPUTATION", line 238
ORA-06512: at "APEX_240100.WWV_FLOW_DYNAMIC_EXEC", line 1618
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_240100", line 731
ORA-06512: at "SYS.DBMS_SYS_SQL", line 1579
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_240100", line 719
ORA-06512: at "APEX_240100.WWV_FLOW_DYNAMIC_EXEC", line 2014
ORA-06512: at "APEX_240100.WWV_FLOW_DYNAMIC_EXEC", line 1511
ORA-06512: at "APEX_240100.WWV_FLOW_DYNAMIC_EXEC", line 1634
ORA-06512: at "APEX_240100.WWV_FLOW_COMPUTATION", line 109
ORA-06512: at "APEX_240100.WWV_FLOW_COMPUTATION", line 306
error_statement:
select count(*) from OCI_RESOURCES
Developer Toolbar

**Comment by adizohar** [comment]
H Varun,

Your setup on the VM probably failed, can you please login to the compute VM and post the boot.log error ?

**Comment by VARUNADITYAV** [comment]
Hello, i can't find boot.log in OL8, i have uploaded dmesg and /var/log/messages
[dmesg.log](https://github.com/user-attachments/files/17459902/dmesg.log)
[messages.log](https://github.com/user-attachments/files/17459914/messages.log)
Thanks
Venkat

**Comment by adizohar** [comment]
The boot.log was created by the application at /home/opc
Did you install it using the terraform ? or manually ?

**Comment by VARUNADITYAV** [comment]
Hello, i don't find in /home/opc and i have installed it manually.

[opc@usagevm ~]$ pwd
/home/opc
[opc@usagevm ~]$ ls -altr
total 2288
-rw-r--r--. 1 opc  opc      141 May 22 22:07 .bash_profile
-rw-r--r--. 1 opc  opc       18 May 22 22:07 .bash_logout
drwxr-xr-x. 3 root root      17 Oct 18 16:40 ..
drwx------. 2 opc  opc       29 Oct 18 16:40 .ssh
-rw-r--r--. 1 opc  opc      558 Oct 18 17:27 .bashrc
drwxrwxr-x. 2 opc  opc     4096 Oct 18 17:28 ADWCUSG
drwxrwxr-x. 3 opc  opc       18 Oct 18 17:31 oradiag_opc
-rw-rw-r--. 1 opc  opc  2269184 Oct 18 19:23 usage2adw_demo_apex_app.sql
drwxrwxr-x. 3 opc  opc       17 Oct 18 22:01 .cache
drwx------. 4 opc  opc       28 Oct 18 22:01 .local
drwx------. 2 opc  opc       33 Oct 18 22:06 .oci
-rw-rw-r--. 1 opc  opc        1 Oct 18 22:06 suggestion_variable.txt
-rw-rw-r--. 1 opc  opc    21968 Oct 18 22:18 wallet.zip
drwxrwxr-x. 7 opc  opc     4096 Oct 18 22:23 usage_reports_to_adw
-rw-rw-r--. 1 opc  opc    10813 Oct 18 22:23 setup.log
-rw-rw-r--. 1 opc  opc       58 Oct 19 00:02 afiedt.buf
drwx------. 9 opc  opc     4096 Oct 19 00:02 .
-rw-------. 1 opc  opc     3047 Oct 19 03:05 .bash_history
[opc@usagevm ~]$

**Comment by adizohar** [comment]
if you install it manually, you have setup.log, please attach it
Did you follow every step ? and no failure ?

**Comment by VARUNADITYAV** [comment]
13. Execute the python script - usage2adw.py or setup_usage2adw.sh --> SKIPPED as i have done 14 to 18 manually, attached setup.log
[setup.log](https://github.com/user-attachments/files/17460050/setup.log)

# if you want to skip 14 to 18, execute the script /home/opc/usage_reports_to_adw/usage2adw_setup.sh -setup_app

# Load the data:
/home/opc/usage_reports_to_adw/shell_scripts/run_multi_daily_usage2adw.sh

**Comment by adizohar** [comment]
setup.log didn't capture the errors because it was executed manually
Can you run again the /home/opc/usage_reports_to_adw/usage2adw_setup.sh -setup_app
And post the full screen messages or the last error

**Comment by VARUNADITYAV** [comment]
here is the script output with error

1. Read Variables from config.user file.

Running Secret Retrieval from Vault
Starts at 2024-10-21 11:57:17

Connecting to Secret Client Service...
Connected.

ServiceError retrieving secret at get_secret_password !

{'target_service': 'secrets', 'status': 404, 'code': 'NotAuthorizedOrNotFound', 'opc-request-id': 'FC8093E20EE1432897BD6EA4A3FE34B1/5BB1E6FC74252A919FB2C957766910FC/0B97561993A055897273BB007DF7208D', 'message': 'Authorization failed or requested resource not found.', 'operation_name': 'get_secret_bundle', 'timestamp': '2024-10-21T11:57:17.469271+00:00', 'client_version': 'Oracle-PythonSDK/2.135.0', 'request_endpoint': 'GET https://secrets.vaults.us-phoenix-1.oci.oraclecloud.com/20190301/secretbundles/ocid1.vaultsecret.oc1.phx.amaaaaaah6oxlkqapnvzsi7mdjaurnzfgy3pcy2fwiroj5xdl7icpjexrkqq', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_notauthorizedornotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/secretretrieval/20190301/SecretBundle/GetSecretBundle for details on this operation's requirements. If you are unable to resolve this secrets issue, please contact Oracle support and provide them this full error message."}

Error retrieving Secret, Abort

**Comment by adizohar** [comment]
You have issue with below policy, please add it and try again
Allow dynamic-group UsageDownloadGroup to read secret-bundles in compartment {APPCOMP}

**Comment by VARUNADITYAV** [comment]
I have updated the policy, earlier i have at tenancy level

[opc@usagevm ~]$ /home/opc/usage_reports_to_adw/usage2adw_setup.sh -setup_app


#########################################################################################################################
# usage2adw_setup.sh - 24.10.01 - Mon Oct 21 12:10:28 GMT 2024
#########################################################################################################################
LOG = /home/opc/setup.log

1. Read Variables from config.user file.

Running Secret Retrieval from Vault
Starts at 2024-10-21 12:10:30

Connecting to Secret Client Service...
Connected.
Secret Retrieved.
Secret Okay
Secret Retrieved from KMS Vault Service.


2. Generate database wallet and extract.
   Internal LOG=/home/opc/usage_reports_to_adw/log/generate_adb_wallet_20241021_121028.log

##########################################################################################
#                      Running Autonomous Database Generate Wallet                       #
##########################################################################################
Starts at 2024-10-21 12:10:37
Command Line : -ip -dbid ocid1.autonomousdatabase.oc1.phx.anyhqljsh6oxlkqaylhdoab5ziaxurj33x3brtfn4yqozut4phxecbbh7b7q -folder /home/opc/ADWCUSG -zipfile /home/opc/wallet.zip -secret ocid1.vaultsecret.oc1.phx.amaaaaaah6oxlkqapnvzsi7mdjaurnzfgy3pcy2fwiroj5xdl7icpjexrkqq

Connecting to Secret Client Service...
Connected.
Secret Retrieved.

Connecting to Database Client Service...
Connected.

Generating Wallet to /home/opc/wallet.zip
Wallet Downloaded.

Creating Folder /home/opc/ADWCUSG
Folder Created

Unzip Wallet to /home/opc/ADWCUSG
Wallet unzipped to /home/opc/ADWCUSG

Updating sqlnet.ora to /home/opc/ADWCUSG
sqlnet.ora was updated

Completed at 2024-10-21 12:10:40
   Okay.

3. Checking OCI Connectivity using instance principles...
   Executed: python3 check_connectivity.sh
   Internal LOG=/home/opc/usage_reports_to_adw/log/check_connectivity_20241021_121028.log

   Connecting to Identity Service...
   Okay.

   Check Tenancy Details Access...
   Okay.

   Get List of Regions...
   Okay.

   Check running in home region...
   Home    Region = us-phoenix-1
   Current Region = us-phoenix-1
   Okay.

   Check Compartment List Access...
   Okay...

   Check Access to Cost and Usage Object Storage...
Error oci.exceptions.ServiceError
{'target_service': 'object_storage', 'status': 404, 'code': 'BucketNotFound', 'opc-request-id': 'phx-1:e8A1xAfKGmgBLDJYYeKf_rEYGhhOJiNVr5X7POMsoQ8XugoypOsYBWMTmzlBvbTp', 'message': "Either the bucket named 'ocid1.tenancy.oc1..aaaaaaaav3cixb4mqt5htut3aff4odosnlooryltxrikwmosydv7jbwnn2ua' does not exist in the namespace 'bling' or you are not authorized to access it", 'operation_name': 'list_objects', 'timestamp': '2024-10-21T12:10:43.761057+00:00', 'client_version': 'Oracle-PythonSDK/2.135.0', 'request_endpoint': 'GET https://objectstorage.us-phoenix-1.oraclecloud.com/n/bling/b/ocid1.tenancy.oc1..aaaaaaaav3cixb4mqt5htut3aff4odosnlooryltxrikwmosydv7jbwnn2ua/o', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_bucketnotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/objectstorage/20160918/Object/ListObjects for details on this operation's requirements. If you are unable to resolve this object_storage issue, please contact Oracle support and provide them this full error message."}
   Error querying OCI, please check the log /home/opc/usage_reports_to_adw/log/check_connectivity_20241021_121028.log
   Please check the documentation to have the dynamic group and policy correctted
   Once fixed you can rerun the script /home/opc/usage_reports_to_adw/usage2adw_setup.sh

   Script will continue incase creating the database on different tenant or child tenant...

   Internal LOG=/home/opc/usage_reports_to_adw/log/db_creation_user_20241021_121028.log
4. Creating USAGE user on ADWC instance and enable APEX Workspace
   commands executed:
   sqlplus ADMIN/xxxxxxxx@adwcusg_low
   create user usage identified by xxxxxxxxx;
   grant create dimension, connect, resource, dwrole, unlimited tablespace to usage;
   exec apex_instance_admin.add_workspace(p_workspace => 'USAGE', p_primary_schema => 'USAGE');
   Okay.

5. Create Usage2ADW Tables
   Internal LOG=/home/opc/usage_reports_to_adw/log/create_tables_20241021_121028.log
   Okay.

6. Enable APEX Application.
   Internal LOG=/home/opc/usage_reports_to_adw/log/enable_apex_application_20241021_121028.log
ORA-20001: Package variable g_security_group_id must be set.
ORA-20001: Package variable g_security_group_id must be set.
ORA-01403: no data found
ORA-20001: Package variable g_security_group_id must be set.
   Error enabling APEX Application, please check log /home/opc/usage_reports_to_adw/log/enable_apex_application_20241021_121028.log, aborting.
[opc@usagevm ~]$

**Comment by adizohar** [comment]
Looks like you don’t have access to the usage files or you are running on a child tenant, please add the correct policies from the documentation

**Comment by VARUNADITYAV** [comment]
I don't have a child tenancy. I have followed the steps 2 and 3 for creating dynamic group and policy, what is the meaning of access to the usage files?

**Comment by VARUNADITYAV** [comment]
Can you share the architecture diagram, how this VM and ADB connect, and overall DFD as well? it is looking for object storage and says that BucketNotFound

**Comment by adizohar** [comment]
The VM download the cost and usage files from object storage biling namespace, you will need to have permission to do it
Please check the documentation - https://docs.oracle.com/en-us/iaas/Content/Billing/Concepts/costusagereportsoverview.htm

Based on the error you got, the policy is and dynamic group not set properly, can you please share printscreen of the dynamic group and the policy ? if you are using different IAM Domains make sure you specify the domain name before group name

**Comment by VARUNADITYAV** [comment]
![dynamic_group](https://github.com/user-attachments/assets/7f880a1a-c3f5-4fae-a0c0-b0137993dd3e)
![usage_policy](https://github.com/user-attachments/assets/4fc9c504-7fe9-4f0b-abec-1a4fdc31119d)
attached the requested details

**Comment by VARUNADITYAV** [comment]
Can we have a quick call in MS teams? it would be easy for me to share the screen

**Comment by adizohar** [comment]
Please fix the policy to include the proper tenancy of the biling namespace (This should not be changed to your tenant id)
```
define tenancy usage-report as ocid1.tenancy.oc1..aaaaaaaaned4fkpkisbwjlr56u7cj63lf3wffbilvqknstgtvzub7vhqkggq
```
Happy to do Teams, but I have back to back meetings today, let try to solve it here, if not we can schedule meeting for tomorrow.

**Comment by adizohar** [comment]
Once fixed please run: 
I noticed you didn't add limit to the usage download date, therefore, it will download everything which can take very long
If you want to limit to 2024-01 please update /home/opc/usage_reports_to_adw/config.user
/home/opc/shell_scripts/run_multi_daily_usage2adw.sh

**Comment by adizohar** [comment]
You setup the apex manually, therefore you won't be able to complete the shell apex setup, you can ignore this error, please run
```
/home/opc/shell_scripts/run_multi_daily_usage2adw.sh
```

**Comment by VARUNADITYAV** [comment]
./run_multi_daily_usage2adw.sh ran successfully, Press on the application "Usage and Cost Report", getting the same error

Error processing computation.
Technical Info (only available for developers)
is_internal_error: true
apex_error_code: APEX.COMPUTATION.UNHANDLED_ERROR
ora_sqlcode: -942

ora_sqlerrm: ORA-00942: table or view "WKSP_CFBFCC2Z2ZFM"."OCI_RESOURCES" does not exist
ORA-06512: at "APEX_240100.WWV_FLOW_COMPUTATION", line 317
ORA-06512: at "APEX_240100.WWV_FLOW_COMPUTATION", line 238
ORA-06512: at "APEX_240100.WWV_FLOW_DYNAMIC_EXEC", line 1618
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_240100", line 731
ORA-06512: at "SYS.DBMS_SYS_SQL", line 1579
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_240100", line 719
ORA-06512: at "APEX_240100.WWV_FLOW_DYNAMIC_EXEC", line 2014
ORA-06512: at "APEX_240100.WWV_FLOW_DYNAMIC_EXEC", line 1511
ORA-06512: at "APEX_240100.WWV_FLOW_DYNAMIC_EXEC", line 1634
ORA-06512: at "APEX_240100.WWV_FLOW_COMPUTATION", line 109
ORA-06512: at "APEX_240100.WWV_FLOW_COMPUTATION", line 306

Merging statistics into OCI_COST_STATS...
   Merge Completed, 8980 rows merged, Process Time 00:00:01

Merging statistics into OCI_PRICE_LIST...
   Merge Completed, 45 rows merged, Process Time 00:00:01

Update OCI_PRICE_LIST for empty currency...
   Merge Completed, 6 rows merged, Process Time 00:00:00

Merging statistics into OCI_COST_REFERENCE ...
   Merging statistics from OCI_COST...
   Merge Completed, 98 rows merged, Process Time 00:00:04
   Handling Tag Special Key 'Oracle-Tags.CreatedBy'
   Merge Completed, 1 rows merged, Process Time 00:00:00

Check OCI_TENANT for new TENANT_ID...
   Update Tenant Display Name Table, 1 rows inserted, Process Time 00:00:00
   Update Current Tenant Name, 1 rows Updated, Process Time 00:00:00

Merging Public Rates into OCI_RATE_CARD...
   Update Completed, 37 rows updated., Process Time 00:00:21

Completed at 2024-10-21 16:07:12
Finish Mon Oct 21 16:07:12 GMT 2024 - local
Completed at Mon Oct 21 16:07:12 GMT 2024..

**Comment by adizohar** [comment]
The only reason your APEX does not work, the APEX does not see the usage tables
You may created the workspace pointing to a different owner, you need to make sure it points to the user that has the tables
Because you installed it manually, you will need to check the APEX documentation how to do it.

**Comment by VARUNADITYAV** [comment]
I have dropped the workspace and re-ran the scripts. all working fine. thanks

**Comment by adizohar** [comment]
Perfect thank you
