### ISSUE TITLE
usage2adw.py optional arguments -dst DSECRET_PROFILE

### ISSUE THREAD

**Issue by edwjack** [oracle-samples/usage-reports-to-adw#7]
Good Day,

We appreciate for your effort.

I was confused about what to input in this field - **ADB Application Secret Tenant**

![image](https://github.com/oracle-samples/usage-reports-to-adw/assets/85690869/bee3b005-fac5-4b64-8201-ecda2c30d8fa)

Could you please provide more detailed explanations on how to utilize it?

-dst DSECRET_PROFILE  ADB Secret tenancy profile (local or blank = instant principle)

**Comment by adizohar** [comment]
Hi,
```
-ds is the parameter for the secret ocid
-dst is the parameter for the tenant profile where the secret is located, if you are using instance principle, please use "local"
```

Usage2ADW can support multi tenancies, therefore need to know where (which tenancy) to query the secret

I will amend the documentation

Please let me know if this answer the question

Thank you

**Comment by edwjack** [comment]
Do you mean profile name in this config file?

![image](https://github.com/oracle-samples/usage-reports-to-adw/assets/85690869/e32f2aa2-ec0a-40bb-a276-b7df960c7662)

**Comment by adizohar** [comment]
If you use profile in the config file for authentication, then yes, use the profile name like APEX or DEFAULT
if you use instance principle authentication (using dynamic groups..), then put "local"

**Comment by edwjack** [comment]
Thank you very much! It's clear.

**Comment by adizohar** [comment]
Thank you for the info, I have amended the documentation and will push the changes later today.
